import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import MainLayout from "../../../layouts/MainLayout.jsx";
import Button from "../../../components/Button.jsx";
import Badge from "../../../components/Badge.jsx";
import Avatar from "../../../components/Avatar.jsx";
import Input from "../../../components/Input.jsx";
import { projects, statusVariant } from "../../../mock/projectData.js";

export default function ProjectListPage() {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("전체");
  const filtered = useMemo(() => projects.filter((p) => (filter === "전체" || p.status === filter) && p.title.toLowerCase().includes(query.toLowerCase())), [query, filter]);
  return <MainLayout><div className="mx-auto max-w-5xl"><header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-wider text-active">PROJECTS</p><h1 className="mt-2 text-3xl font-bold text-primary">프로젝트</h1><p className="mt-2 text-sm text-muted">팀과 AI가 함께 진행하는 모든 업무를 확인하세요.</p></div><Link to="/projects/new"><Button>＋ 새 프로젝트</Button></Link></header><div className="mb-6 flex flex-col justify-between gap-3 border-b border-border pb-4 sm:flex-row"><div className="flex gap-1 overflow-auto">{["전체", "진행중", "검토중", "완료"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-md px-3 py-2 text-sm ${filter === item ? "bg-primary text-white" : "text-muted hover:bg-white"}`}>{item}</button>)}</div><div className="w-full sm:w-56"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="프로젝트 검색" /></div></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((project, index) => <article key={project.id} className="overflow-hidden rounded-xl border border-border bg-white"><Link to={`/projects/${project.id}`} className={`block h-32 p-4 ${index % 3 === 0 ? "bg-active" : index % 3 === 1 ? "bg-success" : "bg-primary"}`}><span className="text-xs font-semibold text-white/70">0{index + 1}</span><strong className="mt-10 block text-xl font-bold text-white">{project.title.split(" ")[0]}</strong></Link><div className="p-4"><div className="flex items-center justify-between"><Badge variant={statusVariant[project.status]}>{project.status}</Badge><span className="text-xs text-muted">{project.updated}</span></div><Link to={`/projects/${project.id}`} className="mt-4 block font-bold text-primary">{project.title}</Link><p className="mt-2 h-9 text-xs leading-5 text-muted">{project.description}</p><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="-space-x-2 flex">{project.members.map((name) => <Avatar key={name} name={name} size="sm" />)}</span><small className="text-muted">할 일 {project.tasks}</small></div></div></article>)}</div>{filtered.length === 0 && <p className="rounded-xl border border-dashed border-border p-12 text-center text-sm text-muted">검색 결과가 없어요.</p>}</div></MainLayout>;
}
