import { useParams } from "react-router-dom";
import MainLayout from "../../../../layouts/MainLayout.jsx";
import Badge from "../../../../components/Badge.jsx";
import Avatar from "../../../../components/Avatar.jsx";
import Tab from "../../../../components/Tab.jsx";
import { projects, statusVariant } from "../../../../mock/projectData.js";

function ProjectOverview({ project }) { return <div className="grid gap-6 lg:grid-cols-[1fr_250px]"><div><section className="rounded-xl border border-border bg-white p-6"><div className="flex items-center justify-between"><span className="flex items-center gap-3"><Avatar name="AI 팀원" size="md" /><span><strong className="block text-sm">AI 팀원</strong><small className="text-xs text-muted">3분 전</small></span></span><Badge>오늘의 브리핑</Badge></div><h2 className="mt-6 text-xl font-bold text-primary">이 프로젝트에서 밤사이 있었던 일</h2><p className="mt-2 text-sm leading-6 text-muted">로그인 정책 변경으로 인증 방식이 조정됐고, 관련 가이드 문서가 수정되었습니다.</p><div className="mt-5 grid grid-cols-3 border-y border-border py-4 text-center text-xs text-muted"><span><strong className="block text-lg text-active">2</strong>영향 작업</span><span><strong className="block text-lg text-active">3</strong>새 회의록</span><span><strong className="block text-lg text-active">1</strong>문서 변경</span></div><button className="mt-5 text-sm font-semibold text-primary">브리핑 전체 보기 →</button></section><section className="mt-7"><h2 className="text-lg font-bold text-primary">최근 활동</h2><div className="mt-3 divide-y divide-border rounded-xl border border-border bg-white"><div className="p-4"><strong className="text-sm">회의록 업데이트 — API 설계 논의</strong><p className="mt-1 text-xs text-muted">김지원님이 Google Meet 회의록을 추가했습니다.</p></div><div className="p-4"><strong className="text-sm">Notion 문서 변경 — 온보딩 가이드</strong><p className="mt-1 text-xs text-muted">Sarah Lee님이 사용자 플로우를 수정했습니다.</p></div></div></section></div><aside className="space-y-4"><section className="rounded-xl border border-border bg-white p-5"><h3 className="font-bold text-primary">팀원</h3>{project.members.map((name) => <div key={name} className="mt-4 flex items-center gap-2"><Avatar name={name} size="sm" /><span><strong className="block text-xs">{name}</strong><small className="text-xs text-muted">프로젝트 팀원</small></span></div>)}</section><section className="rounded-xl border border-border bg-white p-5"><h3 className="font-bold text-primary">연동 상태</h3><p className="mt-4 text-xs text-muted">● Google Meet · 방금 동기화</p><p className="mt-3 text-xs text-muted">● Notion · 10분 전 동기화</p></section></aside></div>; }

export default function ProjectHomePage() { const { projectId } = useParams(); const project = projects.find((item) => item.id === projectId) ?? projects[0]; return <MainLayout><div className="mx-auto max-w-5xl"><header className="mb-6"><p className="text-xs font-semibold tracking-wider text-active">PROJECT</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold text-primary">{project.title}</h1><Badge variant={statusVariant[project.status]}>{project.status}</Badge></div><p className="mt-2 text-sm text-muted">{project.description}</p></header><Tab tabs={[{ label: "홈", content: <ProjectOverview project={project} /> }, { label: "AI 브리핑 상세", content: <p className="text-sm text-muted">AI 브리핑 상세는 팀원이 구현 중입니다.</p> }, { label: "컨텍스트 Q&A", content: <p className="text-sm text-muted">컨텍스트 Q&A는 팀원이 구현 중입니다.</p> }, { label: "팀원 관리", content: <p className="text-sm text-muted">팀원 관리 화면은 팀원이 구현 중입니다.</p> }, { label: "연동 상태", content: <p className="text-sm text-muted">연동 상태 화면은 팀원이 구현 중입니다.</p> }]} /></div></MainLayout>; }
