// ERD for sixpeng
// https://dbml.dbdiagram.io/docs syntax

Table member {
  id bigint [pk, increment]
  email varchar [not null, unique]
  name varchar [not null]
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp
}

Table project {
  id bigint [pk, increment]
  owner_id bigint [not null, ref: > member.id]
  title varchar [not null]
  description text
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp
}
